name: Unit and integration tests
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: |
            3.11
            3.12
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v2
      - name: Install project
        run: uv sync --dev
      - name: Run tests
        run: uv run pytest --cov


    # - name: Upload coverage reports to Codecov
    #   uses: codecov/codecov-action@v4.0.1
    #   if: ${{ matrix.os == 'ubuntu-latest' }}
    #   with:
    #     token: ${{ secrets.CODECOV_TOKEN }}
